apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-rc
spec:
  replicas: 1
  selector:
    app: jenkinsv
  template:
    metadata:
      labels:
        app: jenkinsv
    spec:
      volumes:
      - name: jenkins-shared-data
        hostPath:
           path: /jenkins
      containers:
      - name: jenkins-pod
        image: maha04056/myjenkins:1.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-shared-data
          mountPath: /jenkins