apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-rc-v
spec:
  replicas: 1
  selector:
    app: jenkinsv
  template:
    metadata:
      labels:
        app: jenkinsv
    spec:
      volumes:
      - name: jenkins-shared-data
        hostPath:
           path: /home/ubuntu/jenkins_persistens
      containers:
      - name: jenkins-pod
        image: jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-shared-data
          mountPath:  /var/jenkins_home jenkins