apiVersion: v1
kind: ReplicationController
metadata:
  name: jfrog-rc
spec:
  replicas: 1
  selector:
    app: jfrog
  template:
    metadata:
      labels:
        app: jfrog
    spec:
      containers:
      - name: jfrog-pod
        image: scandio/jfrog-artifactory
        ports:
        - containerPort: 8081
        