apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  selector:
    app: nginx
    version: 1.0
  template:
    metadata:
      labels:
        app: nginx
        version: 1.0
    spec:
      containers:
      - name: nginx-pod
        image: nginx
        ports:
        - containerPort: 80