apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins1svc
spec:
  type: NodePort 
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: jenkins1