apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins1
spec:
  type: NodePort 
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: jenkins1