apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    version: 1.0
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: nginx
    version: 1.0